baseurl = "http://rowanparkinson.com/"
canonifyurls = true
contentdir = "content"
googleAnalytics = "UA-XXXXXXX-Y"
languageCode = "en-us"
layoutdir = "layouts"
publishdir = "public"
theme = ""
title = "Rowan Parkinson"
[[menu.main]]
name = "Contact"
pre = "chat"
url = "contact"
[[menu.main]]
name = "About"
pre = "info"
url = "about"
[params.meta]
author = "Rowan Parkinson"
description = "The work of Melbourne based Web Developer, Rowan Parkinson."
keywords = "Websites, JavaScript, HTML, CSS, Front-End Developer, Front End Developer, Web Developer, Web Development, Developer"
[params.panelone.about]
headline = "About"
intro = "Hi, I'm Rowan, a problem-solving, UX-focussed front-end developer with over 6 years of commercial experience and an excellent eye for detail."
text = "I enjoy making things with Javascript, HTML and CSS. I live in Melbourne and am curently a senior developer at MYOB. If you'd like to get in touch, please check the contact panel."
[params.panelone.skills]
headline = "Skills"
[[params.panelone.skills.icons]]
label = "CSS"
proficiency = "9"
svgIcon = "css"
[[params.panelone.skills.icons]]
label = "HTML"
proficiency = "10"
svgIcon = "html"
[[params.panelone.skills.icons]]
label = "JavaScript"
proficiency = "6"
svgIcon = "javascript"
[[params.panelone.skills.icons]]
label = "Git"
proficiency = "7"
svgIcon = "git"
[[params.panelone.skills.icons]]
label = "Illustrator"
proficiency = "2"
svgIcon = "illustrator"
[[params.panelone.skills.icons]]
label = "Photoshop"
proficiency = "5"
svgIcon = "photoshop"
[[params.panelone.skills.icons]]
label = "Terminal"
proficiency = "7"
svgIcon = "terminal"
[params.paneltwo.contact]
headline = "Contact"
realemail = "rowan.parkinson@gmail.com"
[params.paneltwo.contact.button]
reset = "Reset"
submit = "Send"
[params.paneltwo.contact.email]
text = "Email *"
warning = "Please, enter your email."
[params.paneltwo.contact.message]
text = "Message *"
warning = "Please, enter your message"
[params.paneltwo.contact.name]
text = "Name *"
warning = "Please, enter your name"
[params.paneltwo.copyright]
text = "Rowan Parkinson. All rights reserved."
[params.paneltwo.info]
headline = "Get in touch testing"
text = "If you are interested in a new project, collaboration, or a reason to get a beer don't hesitate to shoot me an email via the contact form."
[params.paneltwo.social]
headline = "Follow me"
[[params.paneltwo.social.links]]
label = "Codepen"
svgIcon = "codepen"
url = "http://codepen.io/row-n/"
[[params.paneltwo.social.links]]
label = "Twitter"
svgIcon = "twitter"
url = "https://twitter.com/rowanparkinson"
[[params.paneltwo.social.links]]
label = "Github"
svgIcon = "github"
url = "https://github.com/row-n"
[[params.paneltwo.social.links]]
label = "Lastfm"
svgIcon = "lastfm"
url = "https://www.last.fm/user/mispic"
[[params.paneltwo.social.links]]
label = "NPM"
svgIcon = "npm"
url = "https://www.npmjs.com/~row-n"
[[params.paneltwo.social.links]]
label = "Stack Overflow"
svgIcon = "stackoverflow"
url = "https://stackexchange.com/users/1894495/row-n"
[[params.paneltwo.social.links]]
label = "LinkedIn"
svgIcon = "linkedin"
url = "https://www.linkedin.com/in/rowan-parkinson-87419a30/"
