# Settings
# -----------

baseurl = "http://rowanparkinson.com/"
languageCode = "en-us"
title = "Rowan Parkinson"
contentdir = "content"
layoutdir = "layouts"
publishdir = "public"
canonifyurls = true
theme = ""
googleAnalytics = "UA-XXXXXXX-Y"

# Menu
# -------

[[menu.main]]
    name = "About"
    url = "about"
    pre = "info"

[[menu.main]]
    name = "Contact"
    url = "contact"
    pre = "chat"

# Params
# ---------

[params]

    # Panel One
    # ------------

    [params.panelOne]

        # About
        # --------

        [params.panelOne.about]
            headline = "About"
            intro = "Hi, I'm Rowan, a problem-solving, UX-focussed front-end developer with over 6 years of commercial experience and an excellent eye for detail."
            text = "I enjoy making things with Javascript, HTML and CSS. I live in Melbourne and am curently a senior developer at MYOB. If you'd like to get in touch, please check the contact panel."

        # Skills
        # ---------
        # Skills proficiency is a range from 0 - 10.

        [params.panelOne.skills]
            headline = "Skills"

            [[params.panelOne.skills.icons]]
                label = "CSS"
                proficiency = "9"
                svgIcon = "css"

            [[params.panelOne.skills.icons]]
                label = "HTML"
                proficiency = "10"
                svgIcon = "html"

            [[params.panelOne.skills.icons]]
                label = "JavaScript"
                proficiency = "6"
                svgIcon = "javascript"

            [[params.panelOne.skills.icons]]
                label = "Git"
                proficiency = "7"
                svgIcon = "git"

            [[params.panelOne.skills.icons]]
                label = "Illustrator"
                proficiency = "2"
                svgIcon = "illustrator"

            [[params.panelOne.skills.icons]]
                label = "Photoshop"
                proficiency = "5"
                svgIcon = "photoshop"

            [[params.panelOne.skills.icons]]
                label = "Terminal"
                proficiency = "7"
                svgIcon = "terminal"


    # Panel Two
    # ------------

    [params.panelTwo]

        # Info
        # -------

        [params.panelTwo.info]
            headline = "Get in touch"
            text = "If you are interested in a new project, collaboration, or a reason to get a beer don't hesitate to shoot me an email via the contact form."

        # Social
        # ---------

        [params.panelTwo.social]
            headline = "Follow me"

            [[params.panelTwo.social.links]]
                label = "Codepen"
                url = "http://codepen.io/row-n/"
                svgIcon = "codepen"

            [[params.panelTwo.social.links]]
                label = "Twitter"
                url = "https://twitter.com/rowanparkinson"
                svgIcon = "twitter"

            [[params.panelTwo.social.links]]
                label = "Github"
                url = "https://github.com/row-n"
                svgIcon = "github"

            [[params.panelTwo.social.links]]
                label = "Lastfm"
                url = "https://www.last.fm/user/mispic"
                svgIcon = "lastfm"

            [[params.panelTwo.social.links]]
                label = "NPM"
                url = "https://www.npmjs.com/~row-n"
                svgIcon = "npm"

            [[params.panelTwo.social.links]]
                label = "Stack Overflow"
                url = "https://stackexchange.com/users/1894495/row-n"
                svgIcon = "stackoverflow"

            [[params.panelTwo.social.links]]
                label = "LinkedIn"
                url = "https://www.linkedin.com/in/rowan-parkinson-87419a30/"
                svgIcon = "linkedin"

        # Contact
        # ----------

        # Since this template is static, the contact form uses www.formspree.io as a
        # proxy. The form makes a POST request to their servers to send the actual
        # email. Visitors can send up to a 1000 emails each month for free.
        #
        # What you need to do for the setup?
        #
        # - set your email address under 'realEmail' below
        # - upload the generated site to your server
        # - send a dummy email yourself to confirm your account
        # - click the confirm link in the email from www.formspree.io
        # - you're done. Happy mailing!

        [params.panelTwo.contact]
            headline = "Get in touch"
            realEmail = "rowan.parkinson@gmail.com"

            [params.panelTwo.contact.name]
                text = "Name *"
                warning = "Please, enter your name"

            [params.panelTwo.contact.email]
                text = "Email *"
                warning = "Please, enter your email."

            [params.panelTwo.contact.message]
                text = "Message *"
                warning = "Please, enter your message"

            [params.panelTwo.contact.button]
                submit = "Send"
                reset = "Reset"

        # Copyright
        # ------------

        [params.panelTwo.copyright]
            text = "Rowan Parkinson. All rights reserved."

    # Meta
    # -------
    [params.meta]

        description = "The work of Melbourne based Web Developer, Rowan Parkinson."
        author = "Rowan Parkinson"
        keywords = "Websites, JavaScript, HTML, CSS, Front-End Developer, Front End Developer, Web Developer, Web Development, Developer"